// <auto-generated />
namespace ITRACK.models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _remove_order_price : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_remove_order_price));
        
        string IMigrationMetadata.Id
        {
            get { return "201606241141076__remove_order_price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
