// <auto-generated />
namespace ITRACK.models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _Cut_No : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Cut_No));
        
        string IMigrationMetadata.Id
        {
            get { return "201605270521236__Cut_No"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
